# Generated by Django 5.2.4 on 2025-09-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='imagename',
        ),
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
    ]
